// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KQaC8EGHATMtQJ6GeCUMx8fv0wpU9u4',
    appId: '1:992157855862:web:ec7ce7c617cdea8b412f57',
    messagingSenderId: '992157855862',
    projectId: 'my-wallet-d8926',
    authDomain: 'my-wallet-d8926.firebaseapp.com',
    storageBucket: 'my-wallet-d8926.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBLgmmw5rq1TyoFZ6548ZlcxV9nQieig',
    appId: '1:992157855862:android:5a554a9df3249713412f57',
    messagingSenderId: '992157855862',
    projectId: 'my-wallet-d8926',
    storageBucket: 'my-wallet-d8926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_8uk2geod6vNcnBk8qq1Q6igp9ZkZNo',
    appId: '1:992157855862:ios:b728ec86510a6d3d412f57',
    messagingSenderId: '992157855862',
    projectId: 'my-wallet-d8926',
    storageBucket: 'my-wallet-d8926.firebasestorage.app',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_8uk2geod6vNcnBk8qq1Q6igp9ZkZNo',
    appId: '1:992157855862:ios:b728ec86510a6d3d412f57',
    messagingSenderId: '992157855862',
    projectId: 'my-wallet-d8926',
    storageBucket: 'my-wallet-d8926.firebasestorage.app',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1KQaC8EGHATMtQJ6GeCUMx8fv0wpU9u4',
    appId: '1:992157855862:web:68313a0e7f325998412f57',
    messagingSenderId: '992157855862',
    projectId: 'my-wallet-d8926',
    authDomain: 'my-wallet-d8926.firebaseapp.com',
    storageBucket: 'my-wallet-d8926.firebasestorage.app',
  );
}